name: LinkCard function container CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Container Registory
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up variables
      run: |
        echo "repository_name=$(echo ${{ github.repository }} | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV
        echo "tag_name=$(echo ${{ github.ref }} | sed -e 's#refs/tags/##g' | sed -e 's#refs/heads/##g')" >> $GITHUB_ENV

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: tools/ogpfunction
        tags: |
          ghcr.io/${{ env.repository_name }}:${{ env.tag_name }}
